# Generated by Django 3.0.4 on 2020-04-25 11:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions_api', '0001_initial'),
        ('saas_billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptiontransaction',
            options={'ordering': ('date_transaction', 'user')},
        ),
        migrations.AlterModelOptions(
            name='usersubscription',
            options={'ordering': ('user', 'date_billing_start')},
        ),
        migrations.AddField(
            model_name='subscriptiontransaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='how much was billed for the user', max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='subscriptiontransaction',
            name='date_transaction',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 25, 11, 33, 59, 358836), help_text='the datetime the transaction was billed', verbose_name='transaction date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptiontransaction',
            name='paid',
            field=models.BooleanField(default=False, help_text='Mark transaction has paid'),
        ),
        migrations.AddField(
            model_name='subscriptiontransaction',
            name='subscription',
            field=models.ForeignKey(help_text='the Subscription that were billed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.SUBSCRIPTIONS_API_USERSUBSCRIPTION_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptiontransaction',
            name='user',
            field=models.ForeignKey(help_text='the user that this subscription was billed for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='active',
            field=models.BooleanField(default=True, help_text='whether this subscription is active or not'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='cancelled',
            field=models.BooleanField(default=False, help_text='whether this subscription is cancelled or not'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='date_billing_end',
            field=models.DateTimeField(blank=True, help_text='the date to finish billing this subscription', null=True, verbose_name='billing start end'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='date_billing_last',
            field=models.DateTimeField(blank=True, help_text='the last date this plan was billed', null=True, verbose_name='last billing date'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='date_billing_next',
            field=models.DateTimeField(blank=True, help_text='the next date billing is due', null=True, verbose_name='next start date'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='date_billing_start',
            field=models.DateTimeField(blank=True, help_text='the date to start billing this subscription', null=True, verbose_name='billing start date'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='due',
            field=models.BooleanField(default=False, help_text='whether this subscription is due or not'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='plan_cost',
            field=models.ForeignKey(help_text='the plan costs and billing frequency for this user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscriptions_api.PlanCost'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='user',
            field=models.ForeignKey(help_text='the user this subscription applies to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscriptiontransaction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
