# Generated by Django 3.0 on 2020-09-11 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saas_billing', '0002_paypalsubscription_paypalsubscriptionplan_paypalsubscriptionplancost_stripecustomer_stripesubscripti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripesubscription',
            name='session_ref',
        ),
    ]
