# Generated by Django 2.2.16 on 2020-09-15 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saas_billing', '0003_remove_stripesubscription_session_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripecustomer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stripesubscription',
            name='subscription_ref',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
